name: glowapp_frontend
description: GlowApp - N-Back Game & Beauty Platform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Routing
  go_router: ^13.2.0
  
  # Networking & Storage
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  
  # UI & Styling
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  vibration: ^1.8.4 # Para feedback háptico (acierto/error)
  fl_chart: ^0.66.0 # Para los gráficos de estadísticas (Fase 3)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  mockito: ^5.4.4
