server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Compresión Gzip activada
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Deshabilitar caché agresivo para HTML y scripts de arranque (Obliga a celulares a descargar siempre la versión más reciente)
    location ~* (index\.html|flutter_bootstrap\.js|flutter_service_worker\.js)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
        try_files $uri $uri/ /index.html;
    }

    location / {
        # Redirección SPA para Flutter Web (evita 404 al recargar)
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri $uri/ /index.html;
    }

    # Caché de imágenes y fuentes
    location ~* \.(?:css|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2)$ {
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }
}
