server {
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # CompresiÃ³n Gzip activada
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Deshabilitar cachÃ© agresivo para HTML y scripts de arranque (Obliga a celulares a descargar siempre la versiÃ³n mÃ¡s reciente)
    location ~* (index\.html|flutter_bootstrap\.js|flutter_service_worker\.js)$ {
        add_header Cache-Control "no-cache, no-store, must-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires "0";
        try_files $uri $uri/ /index.html;
    }

    location / {
        # RedirecciÃ³n SPA para Flutter Web (evita 404 al recargar)
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri $uri/ /index.html;
    }

    # CachÃ© de imÃ¡genes y fuentes
    location ~* \.(?:css|png|jpg|jpeg|gif|ico|svg|ttf|woff|woff2)$ {
        expires 1d;
        add_header Cache-Control "public, no-transform";
    }
}

