// This file was generated by build_runner.
// Do not modify this file manually.

part of 'context_models.dart';

AvailableContext _$AvailableContextFromJson(Map<String, dynamic> json) {
  return AvailableContext(
    id: json['id'],
    tenantId: json['tenantId'],
    salonId: json['salonId'],
    membership: json['membership'],
    role: json['role'],
  );
}

Map<String, dynamic> _$AvailableContextToJson(AvailableContext instance) {
  final Map<String, dynamic> data = <String, dynamic>{};
  data['id'] = instance.id;
  data['tenantId'] = instance.tenantId;
  data['salonId'] = instance.salonId;
  data['membership'] = instance.membership;
  data['role'] = instance.role;
  return data;
}

ActiveContext _$ActiveContextFromJson(Map<String, dynamic> json) {
  return ActiveContext(
    id: json['id'],
    tenantId: json['tenantId'],
    salonId: json['salonId'],
    membership: json['membership'],
    role: json['role'],
    state: json['state'],
  );
}

Map<String, dynamic> _$ActiveContextToJson(ActiveContext instance) {
  final Map<String, dynamic> data = <String, dynamic>{};
  data['id'] = instance.id;
  data['tenantId'] = instance.tenantId;
  data['salonId'] = instance.salonId;
  data['membership'] = instance.membership;
  data['role'] = instance.role;
  data['state'] = instance.state;
  return data;
}