const bcrypt = require('bcryptjs');

const hash = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewdBPj/RK.PZvO.S';
bcrypt.compare('admin123', hash).then(res => {
  console.log('Result for $2b$ hash:', res);
});

bcrypt.hash('admin123', 10).then(newHash => {
  console.log('New hash generated by bcryptjs:', newHash);
  bcrypt.compare('admin123', newHash).then(res2 => {
    console.log('Result for new hash:', res2);
  });
});
